name: github_reporter
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0-290.1.beta

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  args: ^2.7.0
  github: ^9.25.0
  google_generative_ai: ^0.4.7
  intl: ^0.20.2
  logging: ^1.3.0

dev_dependencies:
  http: ^1.5.0
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.26.3
